name: revolvair
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  data_fixture_dart: ^2.2.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_map: ^5.0.0
  geolocator: ^10.1.0
  http: ^1.1.0
  latlong2: ^0.9.0
  mocktail: ^1.0.0
  multiple_result: ^5.1.0
  stacked: ^3.4.1
  stacked_services: ^1.3.0
  url_launcher: ^6.1.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  stacked_generator: ^1.3.3
  build_runner: ^2.4.6
  # test: ^1.24.3

flutter:
  uses-material-design: true
  assets:
    - ./lib/.env
    - assets/
  